---
chdir: /home/deploy/apps/bg_blitz/current
environment: production
address: localhost
port: 3001
timeout: 30
wait: 30
log: /home/deploy/apps/bg_blitz/shared/log/thin.log
pid: /home/deploy/apps/bg_blitz/shared/pids/thin.pid
socket: /tmp/bg_blitz-thin.sock
max_conns: 1024
max_persistent_conns: 100
require: []
servers: 2
daemonize: true
onebyone: true
